---

# Deployment descriptor
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: "hub"
    app.kubernetes.io/component: "hub"
    app.kubernetes.io/part-of: "hub"
    app.kubernetes.io/instance: "hub-main"
    app.kubernetes.io/version: "3.0.0"
  name: "hub"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hub"
      app.kubernetes.io/component: "hub"
      app.kubernetes.io/part-of: "hub"
      app.kubernetes.io/instance: "hub-main"
      app.kubernetes.io/version: "3.0.0"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path:  "/actuator/prometheus"
        profiles.grafana.com/java.enabled: "true"
        resource.opentelemetry.io/service.name: "hub"
      labels:
        app.kubernetes.io/name: "hub"
        app.kubernetes.io/component: "hub"
        app.kubernetes.io/part-of: "hub"
        app.kubernetes.io/instance: "hub-main"
        app.kubernetes.io/version: "3.0.0"
    spec:
      containers:
      - name: hub
        image: "alainpham/hub:3.0.0"
        imagePullPolicy: "Always"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APPLICATION_NAME
            value: hub
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4318"
          - name: OTEL_JAVAAGENT_ENABLED
            value: "false"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=hub,service.namespace=$(POD_NAMESPACE),service.instance.id=$(POD_NAME),service.version=3.0.0"
        livenessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 0
          successThreshold: 1
          periodSeconds: 10
          failureThreshold: 40 
        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 0
          successThreshold: 1
          periodSeconds: 10
          failureThreshold: 40 
        resources:
          # limits:
          #   cpu: "1.0"
          #   memory: "1024Mi"
          # requests:
          #   cpu: "0.2"
          #   memory: "128Mi"
        ports:
          - containerPort: 8080
          - containerPort: 8081

---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/name: "hub"
    app.kubernetes.io/component: "hub"
    app.kubernetes.io/part-of: "hub"
    app.kubernetes.io/instance: "hub-main"
    app.kubernetes.io/version: "3.0.0"
  name: "hub"
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "hub"
    app.kubernetes.io/component: "hub"
    app.kubernetes.io/part-of: "hub"
    app.kubernetes.io/instance: "hub-main"
    app.kubernetes.io/version: "3.0.0"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub
  labels:
    app.kubernetes.io/name: "hub"
    app.kubernetes.io/component: "hub"
    app.kubernetes.io/part-of: "hub"
    app.kubernetes.io/instance: "hub-main"
    app.kubernetes.io/version: "3.0.0"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: hub.codersandbox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub
            port:
              number: 8080
---
